language: ruby
dist: trusty
sudo: required
jdk:
- openjdk8
rvm:
- 2.4.1

env:
  global:
  - TRAVISCI_SCRIPT_DIR=/tmp/ci_scripts
  - PLANTUML_VERSION=1.2017.15
  - GENERATED_FILE_BRANCH_NAME=tmp_generated
  - GENERATED_FILE_BRANCH_COMMIT_MSG=travisBuild
  - GENERATED_FILE_BRANCH_DIR=/tmp/heroku_app
  - secure: "B3bW5M7MK9Wdx/4zjwMAYGOLA/ZXpwS3FUmLTRgT7XrQg6kQpFEymHsMSZtwX2QNorj6lsgCv5b59dj0E9V9oVIZmYpATtyKX//IHiX2PHSUr/cJ8AH3g/uuJD/56R7LP+B8KU69Cmrh6b38533iLuv/nmwRV2E1HYicEQ4yUoBv6OsTxwGiQkilVhVm6mcsJ0FJQnzJkcpl0Yi0S4DY2f4jk2RLUUoW5XD4FGq03KjgtpxNFaHVyIMUdZsERuM22NcsX7EQp7iLoJxMkr9bvQepbjIOplv8Zje80hujrrq4k2OAH7DToCmpfYQSSTTsnx++feBBFT2tpEHPrQAqGhmgRN5YIQ+ydfB1DSlhmy3eudUyzhE2xXtUTCdBEAjLEnX8dK/OhQwisIeATUx0NkKQIY8gVYRQLcOTrNjEBoO0kdIfW6ZV/fF0gU9V5ReQVGeHycTUcijDss/JpAi03suOMpVBLGGxgluuH91iIzaLOd5Yog90iFoJa6jr7ctgjwqW/49UrhyMoigpUW+fNOcz0EO9Jxbp4DEFzFrx+TVQr1XFMNlbrrC6uvwTpSBgEi+/5ysVdPNsiwF8C2eFqXPRgnzdQYOSmVQitalNXU1wPomh1/kguGKsAYGMvtOrvR2y+9QcRIfIs11CoBXFhPjAxWvOwhGEE8Jrs0JyVw8="

# install dependencies and prepare build structure
before_install:
  # copy build scripts to tmp folder for the tavis.yml
  - mkdir -p $TRAVISCI_SCRIPT_DIR
  - cp -r $TRAVIS_BUILD_DIR/ci_scripts/* $TRAVISCI_SCRIPT_DIR
  - chmod u+x $TRAVISCI_SCRIPT_DIR/*
  # install system build dependencies
  - "$TRAVISCI_SCRIPT_DIR/prepare_system_dependency.sh"

install:
  - bundle install --gemfile=$TRAVIS_BUILD_DIR/jekyll_content/Gemfile

script:
  - cd $TRAVIS_BUILD_DIR/jekyll_content
  - bundle exec rake html_proofer
  - cd $TRAVIS_BUILD_DIR

# create a branch with generated static jekyll files
after_success:
  - "$TRAVISCI_SCRIPT_DIR/prepare_generated_files_branch.sh"

# execute selenium integration tests
after_deploy:
  - cd $TRAVIS_BUILD_DIR
  - git checkout $TRAVIS_BRANCH
  - cd $TRAVIS_BUILD_DIR/integration_test
  - bundle install
  - bundle exec rake test

notifications:
  slack:
    secure: "XTu6lLq4yFeRpMi/jJQY0O66pkXWEI9giINuJGP9Dg/bNn+GwkxaNji02sJHy2JUHjFfk/m42n/A0z6tx3nc6PyDPZMpL1npkREeoGThJkXfFvMJs2aQzLYTnLazBVNAfuplEMSvkTtp/aCM2Yatyw3dRuVOstb1GSg3vetOTiOwL90T3M5ppsQBwBMhwCcszFSEa8HKksfuIHcSdHrjniWu2AzAUACM7IU5M+yXOUpD5ufGo99kXQPfZMC41ze/PQRbvjVGHijW5s7Et8ObMyWCONYQjgj3VjIwgm8wgyHkMLxMQ2vVmyYKfKNoT5ka4KMry2zEzVwkexu4O/bWEynd6LC+0zANxC+FkE7QUFbQaBdoNHK9XdAbfJDl2xLPvo3PbYnGd1+AvK3veN0Z5a5kINGvrO9dGYHpojiCY3Mf+VkBMHO7EM8S3KU6e8ddFZRCO6eEkD7tYqJKrsWFxh0MAxmG4r9luE07Ti4SVTHXb83HddfKx5fDqxnfHs0p/lRhwHx7mF93RO9WQgsMVCb46prpB6H/URQ1zxvbm5TgHVeclHFeuveeSwu7N2+38scOLygppcXItZvw1iqPiG1CtbOe+Qb5eS7O+IRZYzy2OmNiDF3w9O1+T/HN1zCy5DhTfgKDNpHv+lkyuAPMUfa2V9l0Ht+7R1L1lmWOQRY="
jobs:
  include:
  # Build the Jekyll blog as Heroku App
  - stage: Development
    env:
      - JEKYLL_BASEURL=
      - HEROKU_APP_NAME=noltarium-blog-development
      - BLOG_DEPLOY_TEST_URL=https://$HEROKU_APP_NAME.herokuapp.com/
    before_deploy:
      - "$TRAVISCI_SCRIPT_DIR/prepare_heroku_deployment.sh"
      - git checkout herokuapp
    deploy:
      - provider: heroku
        api_key:
          secure: "my2fBYUyvB4mFMh16cPOp7iEWc/MZcd6z2ihVxf2LxPuKkZtP1Wxsx1WNt8GDJY+uiZ4EhZHPn1tLih8DCKxf36+yyHar4TmXJAKewmKUi7EssULehTPAr2pKYwBtTY2ViEWITVVL+8InlTBlSt5XNid8hVNkEYLbOw7y0t2TQ8lAbIvhNJQKJzflQrezIUBx/Nc19DILOkNwbI6YwTlJqQi1r9JhFyQOT9V9jujbfB444KlwGYT9nWCg50hvjZWPZxrhQ/3zhwRLaNbnu/x2J2ACXXTZuMdHauR7PqIYeKuxoQJ9ky7bsQV/8FZPIzqABvrQkNjdJbyofSQO9EUl64Nc/Tgx9HMsGtmbfehgsRjTxhHj6/jxHcMiOiqsFwthFsaOGQSMgP8h535sa807arlkwKsqGSC+etUFdN7qZ5un82U+fgbV8WaJ6C/idtO1ehc3KSmLs6h2ts2d+V85x6pmO1pTPwGvjs9ROoKtd4fDvPWzfe4R0aPqdJys2HAgLLK+NtoOnUpRBChJ4g+6ktMIc5bwAqh/WFsJEW1Sz1V4zOhDBcz7ugUkg1MlciE6t/i5mRJNoAtje/xcPZzMvmRXIUlD8CEyWE4trEPlLjJSDYyl7ty6qOapwG9sG4E2SNMEMQpxiJeCCHsCo3A3ThPr3sQSl7c/fkH1psgdkc="
        app: $HEROKU_APP_NAME
        on:
          all_branches: true
  - env:
      - secure: "dHTqsAaJyRXN7HRdI+/UB+46QwSPkYWlgkVZmoBSVussHy4OlDXLHJ/1BxzR9jEg1fl8EocC9o1aTPpJw7S3yeEvuVGAKIC7nqh7Dyb99n7LMEq4r2jcHbo7/afdlCKOgbw8+lQGQTj7CbqvmJjopSTlrXUzBORWFc92AHR5xYRlkhlJHw+5s/qETT0DMXkzr2mNrw7FQajci58zhOgwtDm5303Ub4PX6xGYXFiSPDJsuNdaP004vFRuM66yCZG7UhVP4Li5ZvcTfnoHWrZdERXsVUdbjuUJn26PzGAjXRwnp7GVA8Km24sJRUqfcO1k72cDg3sSRQSWyDg7LGTQNiJ2DZZeMKBzvd/IdGI6mkXtmKVIKUWA3aHqYkmzNB0wWKPWNImJlCZLjUkTIu5BuVlZN1Vokbi286LFahG7w/N+jfHBT5LM7u3xGZdVkBuqUUGxwEMNhEVp687hIGsazalJxb2JlndFoWRMCoJ55eBBnhZOpBH0yPGY72hnoOuMtpbeN+KFUe7m0srWi6L+4EKwbtZbxP83bGXiT2fvkgsHV1eRaiz7JOVin4hYhutAkV18YyUvqvaO/Z2D+pnfPtNT+fq6kcnV0cPJoTF90/jMAQOokY+0A1IzopIRPZX6onb4WoeB3f89Hj2OmP5cnrJ0v7gGgL0giRsmJQAcO+4="
      - secure: "F0C9a2n4AziEsN6Mj8M/ueWsR0AxukeBO8WWCDNwkQ80jixpYsXnP5C2pKdopr6KdSDiWfDo79gyjhe/3cXXyVxrBVxtt684gsKT17+NuHEFUK9ueaUYUk8OHF4k6RUeFxFCueCWlpYw6Yo+Rw7jfq4ZQKRjitin2jpro3cLrNM7EbI2w+qBjlec0xl/pbEj1kD12nnUt4P+Z082GZftD39HgyDrS4E25AZeI4IfIl4yZnNQGmAwUpiHdF/Q5R5luiBFP5p+yqYqMo7ioL+9uS7TnKs/YaGOdwdNks6ZAnPZ7e6ObwcjdRuohU0CYXNqyEcmIBx3py6uMQQv4MACjw6bXvCwVfDtFVi2HkNqVzYcOmlpnDH+MBiuP999DT4a0xB2dM0KlRGovsydpWPcoKa7fLvpTSD+rzYiBTtOU1YdAij3WfyZrE4Dp7HGEtdBPNTzcVZi59H+loIx+p4R/TnNblppXD8NENgfGK9nMpgE3Svg7ukHHsIhSLxE9urPuQqyJYYajgEmqA8DkK4IZhhBdK+keJKioQmIdJ8zXhyX229MJDBC+6dc5bq5CCD9HPpZC+I+3fTCyPX21L2Ywnq34Th8Lgrzf4QnDi7p4hBYawYMjIZPRjFe6hBY/VvNcInAKgtkaacuZYPF9OkpGK06BtxMYHBlKS/csuYjPgo="
      - DOCKER_HUB_IMAGE_NAME=bog.noltarium.de
    services:
      - docker
    before_deploy:
      - "$TRAVISCI_SCRIPT_DIR/prepare_docker_nginx_deployment.sh"
      - git checkout dockernginx
    deploy:
          - provider: script
            script: $TRAVISCI_SCRIPT_DIR/deploy_to_dockerhub.sh latest
            on:
              branch: master
          - provider: script
            script: $TRAVISCI_SCRIPT_DIR/deploy_to_dockerhub.sh development
            on:
              branch: development

  - stage: build in docker
    env:
      - JEKYLL_BASEURL=
    services:
      - docker
    before_install: skip
    install: docker build -t jekyll-boilerplate .
    script: docker run -v $(pwd)/jekyll_content:/jekyll_content jekyll-boilerplate exec rake build
    before_deploy: skip
    deploy: skip
    after_success: skip
    after_deploy: skip

  # Build the blog as GithHub Page
  - stage: deploy as gh-page
    env:
      - PROJECT=$(basename $TRAVIS_BUILD_DIR)
      - JEKYLL_BASEURL=\/$PROJECT
      - BLOG_DEPLOY_TEST_URL=https://nolte.github.io/jekyll-boilerplate/
      - GITHUB_PAGE_DIR=/tmp/ghpage
    deploy:
      # only executed on master branch
      - provider: script
        script: $TRAVISCI_SCRIPT_DIR/deploy_ghpage.sh
