language: ruby
dist: trusty
sudo: required
jdk:
- openjdk8
rvm:
- 2.4.1

env:
  global:
  - TRAVISCI_SCRIPT_DIR=/tmp/ci_scripts
  - PLANTUML_VERSION=1.2017.15
  - GENERATED_FILE_BRANCH_NAME=tmp_generated
  - GENERATED_FILE_BRANCH_COMMIT_MSG=travisBuild
  - GENERATED_FILE_BRANCH_DIR=/tmp/heroku_app
  - secure: "JpXTuuZOUICxAcFo9sconF2QPZLO78PERIusC1L7LzYLw3jjYXZCG3q78tuskma0WHc5PUCjwq0hx/6JxqDE3dXbP4wJk7IB+jEUh1ph7xiTsXp41yJxuqhNkwTKwUkFnar8BUaaCNnS/hBPztb4jW4yeHlZNsjgVyNRkWfGsE5WvKcwPxig+jm+B06+uUFLfoEOev9l8jERgzeBMCi/0NTkhlxxIZLW4eLu2WNh43vW+U9jGjXOSVjzBVTUXZnL4g5IxNItBzMn/TzoXfhOlAo1LmKs64cr1OvrCuoGUdcTvLvgmfFPQy6c1NOdruMQNWq/KhHR17qs7UqF4hSMhtXODEt/nItlp8aXFOWZ3cXKBlahNxNnq/8iYqevUlHFhFTQIIQtPQ6WjCCfAT0yNDYRREL317ojYEglehWFRKgMWAuGuO/b2WWl96th0gTk4ynNPY0ad3ASMIg5aazkbHc8CoJ4T+Tr84ixqVci7iG21Am1mgBhpwUDNrpx6bxMci+Z9H4BgURq0+Ku9HspczJINPPzIK9pS2qaJ2U1HP+5LwJb6DNRr3wn4AXeNUXGl8ZXFLjniU4SjdsxEZEm1S8PYfXEgptHovqwOhh6o4u5dZmiDQq2yW5anCIMSpnOnVxBGeSKv1gI2gw6pP7Fy5f8xG2o/WZJC8MSDRh05kA="

# install dependencies and prepare build structure
before_install:
  # copy build scripts to tmp folder for the tavis.yml
  - mkdir -p $TRAVISCI_SCRIPT_DIR
  - cp -r $TRAVIS_BUILD_DIR/ci_scripts/* $TRAVISCI_SCRIPT_DIR
  - chmod u+x $TRAVISCI_SCRIPT_DIR/*
  # install system build dependencies
  - "$TRAVISCI_SCRIPT_DIR/prepare_system_dependency.sh"

install:
  - bundle install --gemfile=$TRAVIS_BUILD_DIR/jekyll_content/Gemfile

script:
  - cd $TRAVIS_BUILD_DIR/jekyll_content
  - bundle exec rake html_proofer
  - cd $TRAVIS_BUILD_DIR

# create a branch with generated static jekyll files
after_success:
  - "$TRAVISCI_SCRIPT_DIR/prepare_generated_files_branch.sh"

# execute selenium integration tests
after_deploy:
  - cd $TRAVIS_BUILD_DIR
  - git checkout $TRAVIS_BRANCH
  - cd $TRAVIS_BUILD_DIR/integration_test
  - bundle install
  - bundle exec rake test

notifications:
  webhooks: https://keenio-gateway.herokuapp.com/build
  slack:
    secure: "lPqWfuGviSb0qKl8XTDWRJ90+2Ha949W5NZ/nR3xAzamoHNOjSeoOwJi+YA0n/45Tf4xw+1SmrszIUTPgKckX/b/8hPOwu/VKoxLt77BbZKZizPCklVFCAnuBNuzBXiukl/5z8Dvz5kJipNJWQAK+emkn4HjdHUIGzsqnrSW9gvg0fdUGBndgliquKOZ3MXDsCD0BVBQYSZsqNIvL3JpNbY6mA3ieP8CnKtajx8CrTSEbD6aMg4eaU3/0jtZw/eBsAkw6GvRENt2lLWhgEz3hVZbR3gw6O1hlHz8jqn/3C4yBUjpHxXISMLrU06tlFMeIJBPRFikK/DvyU1RJWM/lNKPEFtJXcFKfduMmbNngHZbjQTsy37MrGDn2FYbSu0V5vp8s+oqZUOq2bFTBn7XdfdaDUAo7QT662Sob12bbjlai/FRigndD7Ga6Os20mFGoVwkyiJ3wXNvEeAzzVjAjVs1MfYHXAaX1V5zIk0w5ki/yCXdOFQJVAp0wDMkBUdGrtff2CGUQhNKkz61DbogTvAZ7Ih3aqYckMQ1cRy06ipRwO+sEh2OgCujQSZ+f/s6NCtRm3tkpJdhQ25xL2r0Fn+wln+oHyw+o4NeLjpvPhnpo4a/laWAyFs0Ye1bTzUw79MnboUM+NHq12yZUQeoD6nkYRUVPRghN95IHXi/Ny4="
jobs:
  include:
  # Build the Jekyll blog as Heroku App
  - stage: Development
    env:
      - JEKYLL_BASEURL=
      - HEROKU_APP_NAME=noltarium-blog-development
      - BLOG_DEPLOY_TEST_URL=https://$HEROKU_APP_NAME.herokuapp.com/
    before_deploy:
      - "$TRAVISCI_SCRIPT_DIR/prepare_heroku_deployment.sh"
      - git checkout herokuapp
    deploy:
      - provider: heroku
        api_key:
          secure: "PXnLVdhE7wL+3UmtOMcV8luBflfTawmCTxCKCMHb3JY4Zlku6OmhuPSBI/Ork/bro1ThGAYI6/GowsKrTwiC/hwSYlRy15+ST1+sWLCISZM0qu5M0Y9g6OTKlkarL7wcQD6wL6B67gcce9E8lRsx3p9tD7a+jKpUl4EF/v907zgHhDCQ1XO0LVQTf2XEd7X0A05AMiCyIbz3JFRDHGwj1LkqIcjEPge1KAhn2BjNTaIdTJq5lkN5bq6aHxx1w6HCZriEgsJaZh1h6b6RTBL/PJ7D+32Ezn+P/cPeUBAfUK9J0Ka5dZGgEFkMFW+LmAg6oAcnBlf6Eax1W2jSy8rpEOVelXUvc7ebF7hMMJrTlg/2728aywXgGEPzCE5S0gI4WD8REoxyNQ9x8bw1c+EtnK1jDz6Lp5AUv9c5ZXAiIA+kPhL+6hA8q4gxRueX5kDou/i/kVrfFSAc5VriKYoce0R3O8P7D0bdAuWiFammSRGnAFIIK7spghywrSWuE+sJ513y3VmfPtBFkEEpIh0f0hfiS1kpywj5xPLj0O6OANGUwvchKqJaHAIGwrgST79bJsZScSUJvWQaYLv3hgtfKVCEyd/g1GxGg0bI/YOp62XliOO+l7byHGkE/wTXeSAgdJ5pkDisiSJ4znboeUuTEgAtVLxNyYz0gjnG0gxOxNM="
        app: $HEROKU_APP_NAME
        on:
          all_branches: true
  - env:
      - secure: "1uCJyiFknRHlXZNCnz9bTCHAzQbMkJfjZbWhRpDE49qLGcwRTYTn2wa8al6yPpYRrRVT26B358eW8fiHyZWsZO8QZEf2dZ1SLzKaNu83CYlhCcDDUMfkDcIZp/nN37eCBS+cXcKRnhg3no92H8cgsfOey2GR833DmzsH0Qbnx5MYQyAPl8SfAucS7yMPdJWI55Nt7HFjl2p5K1Lvccv25TZxGlRM4iO+K8bOwQJuYdhxpFWSzhkmh8LeKN8PmVGDJO7YwAjLF5ojgddNWTJxlFHCTwU46KBcTFBuxYZx+RizXbOayiVk3wx4cYev7OJ8NuGD4L1TBzH1jzkFf6c5PEaw/YncUlhr9Hg2IQc0to1LSgxVxAystFTmRHrsCTbpvZuqXOh2jKlo9NabJaRaGMKfsHOxsVoXDE7ORWrmuiAzTl4f+XrCmxJ5BnnaQqg7BVsofeMXe0WZH40iB6GClzEe/hdEGoiX6brHyV3kl6zvmmy5RjGgamU237nSH3ym2ypPdfGN7ZgoZ9Ql9qePoxjTYv+SZnYhuZ3MATsOiAOo84z64hNffsWlXARxbVubOvW386SoBPvyD5TgQcLurEqAqttRWZEqsWU4kjUnShkVF0dQIENmZO4AXydooFy0kr0tIbzFKMYCeYFglj81mRWcw+5CsmF2lvoog8ziXFg="
      - secure: "XfTl8Ej7OD5dIs5SADaoNG7+yL/zsthDWP/oMGmvQh0DjJ2baP14iBaMSO7tVyZyCXh3REfsFfWcUOxj2Z0+Kv+VPdWjZUcq+iduaigOh5LR8k65S5qAp0dA2wl2y+W/id0qf6El4j5bbmlbSo0D4rPdmPNlwMG26AjXA+od8maD+Ram1m+gPkDBo4JJGnxU+xUg7ZYcepwtuJV/8wfTs8/Jjldz95Ci4toNunOpyep2x0nnN3WRDUPeK8iLyGUvqdJGiuP7GWs7BQc0iJcXhHTV3qA7jCNpralvHNihk117MO5uCi2JtRqtsgAlLHkROAVXsj+KBdcWKW+GM/IHJAKY5F2DT2MxrRTgjp3O2tAX9SvzO7a0k0rXZ4XTQG2qdkr8NxZRvCps/0QeYJoqPAkDu/tedwdawi+vKKZp7TDIo/g2D3d0LgF6rfKbx5x1OP7OCmTSrMZda5DMBUi2Bmu0ByxsuD8qBN5wUdzZqWnRaL2X0NwR4ZZhajewgT15KwPZAopnwqwFB9zrCIz3S1JhGN3uN3Qr7CNYKaO84BGrDQnjx67VOFd8fXybtGJ0XS7h75/bEfuir1knNoTYfYRLXdeC0YDwtkGSB3bd89aHoSdgMvEMDcvn1J1BcIDOOpwtJzAEDG93laH+3ZMt5LwMAFAI+JND8VUBAEIgU0Y="
      - DOCKER_HUB_IMAGE_NAME=bog.noltarium.de
    services:
      - docker
    before_deploy:
      - "$TRAVISCI_SCRIPT_DIR/prepare_docker_nginx_deployment.sh"
      - git checkout dockernginx
    deploy:
          - provider: script
            script: $TRAVISCI_SCRIPT_DIR/deploy_to_dockerhub.sh latest
            on:
              branch: master
          - provider: script
            script: $TRAVISCI_SCRIPT_DIR/deploy_to_dockerhub.sh development
            on:
              branch: development

  - stage: build in docker
    env:
      - JEKYLL_BASEURL=
    services:
      - docker
    before_install: skip
    install: docker build -t jekyll-boilerplate .
    script: docker run -v $(pwd)/jekyll_content:/jekyll_content jekyll-boilerplate exec rake build
    before_deploy: skip
    deploy: skip
    after_success: skip
    after_deploy: skip

  # Build the blog as GithHub Page
  - stage: deploy as gh-page
    env:
      - PROJECT=$(basename $TRAVIS_BUILD_DIR)
      - JEKYLL_BASEURL=\/$PROJECT
      - BLOG_DEPLOY_TEST_URL=https://nolte.github.io/noltarium-blog/
      - GITHUB_PAGE_DIR=/tmp/ghpage
    deploy:
      # only executed on master branch
      - provider: script
        script: $TRAVISCI_SCRIPT_DIR/deploy_ghpage.sh
